name: project name
main: index.html
description: My simple visual novel
version: 0.0.1
author: username
homepage: http://example.com
window:
  width: 600
  height: 400
  min_width: 600
  min_height: 400
  max_width: 600
  max_height: 400
  frame: true
  toolbar: false
  charset: utf-8